### ISSUE TITLE
record video

### ISSUE THREAD

**Issue by emirbeytekin** [mcgraw/dojo-custom-camera#5]
hello
how can i record video this framework ?

**Comment by mcgraw** [comment]
This is not a library/framework. It's an example that followed a tutorial I wrote in the past. I am considering a new tutorial that will cover video so feel free to follow me over on Twitter to learn when that goes live twitter.com/xmcgraw. 

For now, I'd browse https://github.com/vsouza/awesome-ios for an actual library.
